name: Build Binaries

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

jobs:

  job_upload:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Set environment
        run: |
          node ./scripts/set-git-tag-env.js
          echo ${{ github.ref }}
          echo $GH_TAG
          echo $GITHUB_REF


