name: Build Docker

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run
        run: |
          echo "I ran! ${{ github.event }}"


      - name: Create Release
        if: startsWith( github.ref, 'refs/tags/' ) # Run on tags only.
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Create Release
        if: startsWith( github.ref, 'refs/heads/' ) # Run on master only.
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: master-$(git rev-parse --short HEAD)
          release_name: Release master-$(git rev-parse --short HEAD)
          draft: true
          prerelease: true


      - name: run
        run: |
          echo $${{ steps.create_release.outputs.upload_url }}
