name: Build Docker

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run
        run: |
          echo "I ran! ${{ github.event }}"
          cat ${{ github.event_path }}

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: Commit $(git rev-parse --short HEAD) on master. ${{ github.event.head_commit.message }}\n ${{ github.event.head_commit.url }}


      - name: "Set environment: master"
        if: startsWith( github.ref, 'refs/heads/' ) # Run on master only.
        run: |
          echo "::set-env name=PRERELEASE::true"
          echo "::set-env name=TAG_NAME::master-$(git rev-parse --short HEAD)"

      - name: "Set environment: tag"
        if: startsWith( github.ref, 'refs/tags/' ) # Run on master only.
        run: |
          echo "::set-env name=PRERELEASE::false"
          echo "::set-env name=TAG_NAME::$(git describe --tags)"


      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: true
          prerelease: ${{ env.PRERELEASE }}


      - name: run
        run: |
          echo $${{ steps.create_release.outputs.upload_url }}
