name: Build Docker

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:

  build:
    name: Fail test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment
        run: |
          echo "::set-env name=BUILD_FAIL::true"

      - name: Step to fail
        continue-on-error: true
        run: return 2 && echo "::set-env name=BUILD_FAIL::false"

      - name: Did it fail?
        if: $BUILD_FAIL
        run: echo It failed


  test:
    name: Continue
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Continue
        run: echo We carried on
