name: Build Docker

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'

jobs:

  build:
    name: Fail test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Step to fail
        run: zip --version

      - name: Did it fail?
        if: env.BUILD_FAIL == 'true'
        run: |
          echo It failed
          echo ${{ env.BUILD_FAIL }}
          echo $(${{ env.BUILD_FAIL }} == true)

  test:
    name: Continue
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Continue
        run: echo We carried on
