on:
  release:
    types: [published]

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run
        run: |
          echo "I ran! ${{ EVENT_PAYLOAD.repository.name }}"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: printf "The project {{ EVENT_PAYLOAD.repository.name }}@{{ EVENT_PAYLOAD.release.tag_name }} has been deployed. Check out the %s at {{ EVENT_PAYLOAD.release.html_url }}" $(if {{ EVENT_PAYLOAD.release.prerelease }}; then echo "prerelease"; else echo "release"; fi)
